# Generated by Django 2.0.3 on 2018-03-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='Title goes here', max_length=48),
        ),
    ]
