# Generated by Django 2.0.3 on 2018-03-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0002_article_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['panel', 'article_type']},
        ),
        migrations.AlterModelOptions(
            name='panel',
            options={'ordering': ['ordinal']},
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('intro', 'Introduction'), ('fore', 'Foreground'), ('back', 'Background')], default='intro', max_length=12),
        ),
    ]
