# Generated by Django 2.0.3 on 2018-04-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0004_auto_20180403_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='ordinal',
            field=models.IntegerField(default=99, verbose_name='Panel number'),
        ),
    ]
