# Generated by Django 2.0.3 on 2019-02-10 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0006_panel_panel_blurb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['panel', '-article_type']},
        ),
    ]
