# Generated by Django 2.0.3 on 2018-04-10 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panels', '0004_auto_20180403_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learnmore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learnmore_type', models.CharField(choices=[('object', 'Object'), ('slideshow', 'Slideshow'), ('today', 'Today'), ('video', 'Video Story'), ('visit', 'Visit'), ('voices', 'Voices')], default='object', max_length=12)),
                ('slug', models.SlugField(max_length=48, unique=True, verbose_name='short name')),
                ('title', models.CharField(default='Title goes here', max_length=48)),
                ('caption', models.TextField(blank=True, default='')),
                ('narrative', models.TextField(blank=True, default='')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panels.Article')),
            ],
        ),
    ]
