# Generated by Django 2.0.3 on 2018-04-12 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_num', models.IntegerField()),
                ('caption', models.TextField(blank=True, default='')),
                ('narrative', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AlterField(
            model_name='learnmore',
            name='learnmore_type',
            field=models.CharField(choices=[('images', 'Images'), ('objects', 'Objects'), ('today', 'Today'), ('video', 'Video Story'), ('visit', 'Visit'), ('voices', 'Voices')], default='images', max_length=12),
        ),
        migrations.AddField(
            model_name='slide',
            name='learnmore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pops.Learnmore'),
        ),
    ]
