# Generated by Django 2.0.3 on 2018-04-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0002_auto_20180412_1943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['slide_num']},
        ),
        migrations.RemoveField(
            model_name='learnmore',
            name='slug',
        ),
        migrations.AddField(
            model_name='slide',
            name='title',
            field=models.CharField(default='Title goes here', max_length=48),
        ),
    ]
