# Generated by Django 2.0.3 on 2018-04-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0003_auto_20180417_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnmore',
            name='title',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(blank=True, default='', max_length=48),
        ),
    ]
