# Generated by Django 2.0.3 on 2018-04-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0006_auto_20180417_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Today',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('pops.learnmore',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('pops.learnmore',),
        ),
        migrations.AddField(
            model_name='learnmore',
            name='alt_tag',
            field=models.CharField(blank=True, default='', max_length=48, verbose_name='Image description'),
        ),
        migrations.AddField(
            model_name='slide',
            name='alt_tag',
            field=models.CharField(blank=True, default='', max_length=48, verbose_name='Image description'),
        ),
    ]
