# Generated by Django 2.0.3 on 2018-04-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0007_auto_20180423_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('pops.learnmore',),
        ),
        migrations.AlterField(
            model_name='learnmore',
            name='learnmore_type',
            field=models.CharField(choices=[('images', 'Images'), ('objects', 'Objects'), ('today', 'Today'), ('video', 'Video Story'), ('visit', 'Visit'), ('voices', 'Voices')], max_length=12),
        ),
    ]
