# Generated by Django 2.0.3 on 2018-04-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0008_auto_20180423_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnmore',
            name='learnmore_type',
            field=models.CharField(choices=[('images', 'Images'), ('objects', 'Objects'), ('today', 'Today'), ('video', 'Video Story'), ('visit', 'Visit'), ('voices', 'Voices')], default='today', max_length=12),
        ),
    ]
