# Generated by Django 2.0.3 on 2018-04-25 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0006_panel_panel_blurb'),
        ('pops', '0009_auto_20180423_1541'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visit',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('pops.learnmore',),
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('pops.learnmore',),
        ),
        migrations.CreateModel(
            name='Voices',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('pops.learnmore',),
        ),
        migrations.AlterField(
            model_name='learnmore',
            name='learnmore_type',
            field=models.CharField(choices=[('images', 'Images'), ('objects', 'Objects'), ('today', 'Today'), ('video', 'Video Story'), ('voices', 'Voices')], default='today', max_length=12),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48)),
                ('alt_tag', models.CharField(blank=True, default='', max_length=48, verbose_name='Image description')),
                ('caption', models.TextField(blank=True, default='')),
                ('narrative', models.TextField(blank=True, default='')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panels.Article')),
            ],
        ),
    ]
