# Generated by Django 2.0.3 on 2018-04-25 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0006_panel_panel_blurb'),
        ('pops', '0010_auto_20180425_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='article',
        ),
        migrations.AddField(
            model_name='visit',
            name='panel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='panels.Panel'),
            preserve_default=False,
        ),
    ]
