# Generated by Django 2.0.3 on 2019-02-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0013_hotspot_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credits',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('pops.learnmore',),
        ),
        migrations.AlterField(
            model_name='learnmore',
            name='learnmore_type',
            field=models.CharField(choices=[('images', 'Images'), ('objects', 'Objects'), ('credits', 'Credits'), ('today', 'Today'), ('video', 'Video Story'), ('voices', 'Voices')], default='today', max_length=12),
        ),
    ]
